//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HashGo.String.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HashGo.String.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add DineConnect.
        /// </summary>
        public static string DineConnect_Add_Action_Label {
            get {
                return ResourceManager.GetString("DineConnect_Add_Action_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap.
        /// </summary>
        public static string DineConnect_Tap_Label {
            get {
                return ResourceManager.GetString("DineConnect_Tap_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Name.
        /// </summary>
        public static string DineConnect_TennantName_Label {
            get {
                return ResourceManager.GetString("DineConnect_TennantName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to input information.
        /// </summary>
        public static string DineConnect_ToInputInfo_Label {
            get {
                return ResourceManager.GetString("DineConnect_ToInputInfo_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string DineConnect_Url_Label {
            get {
                return ResourceManager.GetString("DineConnect_Url_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ala Carte.
        /// </summary>
        public static string MealOption_AlaCarte_Label {
            get {
                return ResourceManager.GetString("MealOption_AlaCarte_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to make it a meal?.
        /// </summary>
        public static string MealOption_Header_Label {
            get {
                return ResourceManager.GetString("MealOption_Header_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meal It.
        /// </summary>
        public static string MealOption_Meal_Label {
            get {
                return ResourceManager.GetString("MealOption_Meal_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Over.
        /// </summary>
        public static string MenuHome_Footer_StartOver_Label {
            get {
                return ResourceManager.GetString("MenuHome_Footer_StartOver_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Cart / Check Out.
        /// </summary>
        public static string MenuHome_Footer_ViewCart_Label {
            get {
                return ResourceManager.GetString("MenuHome_Footer_ViewCart_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated Waiting Time.
        /// </summary>
        public static string ResturantStart_Estimated_WaitingTime_Label {
            get {
                return ResourceManager.GetString("ResturantStart_Estimated_WaitingTime_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string SelectDiningOption_Cancel_Label {
            get {
                return ResourceManager.GetString("SelectDiningOption_Cancel_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dine In.
        /// </summary>
        public static string SelectDiningOption_DineIn_Label {
            get {
                return ResourceManager.GetString("SelectDiningOption_DineIn_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Dining Option.
        /// </summary>
        public static string SelectDiningOption_Header_Label {
            get {
                return ResourceManager.GetString("SelectDiningOption_Header_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takeaway.
        /// </summary>
        public static string SelectDiningOption_Takeaway_Label {
            get {
                return ResourceManager.GetString("SelectDiningOption_Takeaway_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync.
        /// </summary>
        public static string Sync {
            get {
                return ResourceManager.GetString("Sync", resourceCulture);
            }
        }
    }
}
